### ISSUE TITLE
Puppet lint error no such file or directory rb_sysopen

### ISSUE THREAD

**Issue by pnicaj** [puppetlabs/puppet-lint#197] opened 2024-03-25 14:35 UTC
## Describe the Bug
Was using a tool called ghostbuster and a issue rose with puppet-lint errors

## Expected Behavior
A list of missing puppet code and issues with puppet code.

## Steps to Reproduce
1. Gem install puppet-ghostbuster
2. find . -type f -exec puppet-lint --only-checks ghostbuster_classes,ghostbuster_defines,ghostbuster_facts,ghostbuster_files,ghostbuster_functions,ghostbuster_hiera_files,ghostbuster_templates,ghostbuster_types {} \+

## Environment
 - puppet-lint version: 4.2.3
 - Ruby version:  3.0.2-p107
 - Platform: x86_64-linux-gnu
 - Filepath: ./.git/objects/f4/77b84b1aa1e3009ceb8d0e35208c7f22abb210
 - Filecontents

## Additional Context
Exact error: No such file or directory @ rb_sysopen

**Comment by pmcmaw** [comment] 2024-08-02 10:22
Hey I am not able to reproduce this issue. 

Can you ensure you are running this within an appropriate directory.

I am going to close this issue, as I do not think it is a bug, however if the issue persists or you disagree, please feel free to reopen.

Steps I tried: 
1) Navigated to puppet-lint directory
2) Ran a bundle install
3) Installed the puppet-ghostbuster gem
4) Ran the command `find . -type f -exec puppet-lint --only-checks ghostbuster_classes,ghostbuster_defines,ghostbuster_facts,ghostbuster_files,ghostbuster_functions,ghostbuster_hiera_files,ghostbuster_templates,ghostbuster_types {} +`

**Closed by pmcmaw** 2024-08-02 10:22 UTC
Labels: bug
